### ISSUE TITLE
Does the configuration work for dd.api send metrics call ?

### ISSUE THREAD

**Issue by rahulravindran0108** [DataDog/docker-compose-example#4]
I am using the same configuration as you have in the example. But when running `api.send_metric`, I get the following stack trace:

```
  File "/usr/local/lib/python2.7/dist-packages/datadog/api/api_client.py", line 95, in submit
    if obj_params.get('host', "") == "":
AttributeError: 'str' object has no attribute 'get'
```

I have set api_key, app_key in my options dictionary. Using datadog python client.

**Comment by Jbithell** [comment]
Same issue here - was there a reason it was closed?
